/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CcButton {
        /**
          * Do you want to link a document?
         */
        "href": string | false;
        /**
          * Do you want an primary button?
         */
        "primary": boolean;
    }
}
declare global {
    interface HTMLCcButtonElement extends Components.CcButton, HTMLStencilElement {
    }
    var HTMLCcButtonElement: {
        prototype: HTMLCcButtonElement;
        new (): HTMLCcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "cc-button": HTMLCcButtonElement;
    }
}
declare namespace LocalJSX {
    interface CcButton {
        /**
          * Do you want to link a document?
         */
        "href"?: string | false;
        /**
          * Do you want an primary button?
         */
        "primary"?: boolean;
    }
    interface IntrinsicElements {
        "cc-button": CcButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cc-button": LocalJSX.CcButton & JSXBase.HTMLAttributes<HTMLCcButtonElement>;
        }
    }
}
