/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CcButton {
        /**
          * Do you want to link a document?
         */
        "href": string | false;
        /**
          * Do you want an primary button?
         */
        "primary": boolean;
    }
    interface CcHeadline {
        /**
          * Which rank do you want?
         */
        "rank": number;
    }
    interface CcIcon {
        /**
          * What icon do you need?
         */
        "icon": string;
    }
}
declare global {
    interface HTMLCcButtonElement extends Components.CcButton, HTMLStencilElement {
    }
    var HTMLCcButtonElement: {
        prototype: HTMLCcButtonElement;
        new (): HTMLCcButtonElement;
    };
    interface HTMLCcHeadlineElement extends Components.CcHeadline, HTMLStencilElement {
    }
    var HTMLCcHeadlineElement: {
        prototype: HTMLCcHeadlineElement;
        new (): HTMLCcHeadlineElement;
    };
    interface HTMLCcIconElement extends Components.CcIcon, HTMLStencilElement {
    }
    var HTMLCcIconElement: {
        prototype: HTMLCcIconElement;
        new (): HTMLCcIconElement;
    };
    interface HTMLElementTagNameMap {
        "cc-button": HTMLCcButtonElement;
        "cc-headline": HTMLCcHeadlineElement;
        "cc-icon": HTMLCcIconElement;
    }
}
declare namespace LocalJSX {
    interface CcButton {
        /**
          * Do you want to link a document?
         */
        "href"?: string | false;
        /**
          * Do you want an primary button?
         */
        "primary"?: boolean;
    }
    interface CcHeadline {
        /**
          * Which rank do you want?
         */
        "rank"?: number;
    }
    interface CcIcon {
        /**
          * What icon do you need?
         */
        "icon"?: string;
    }
    interface IntrinsicElements {
        "cc-button": CcButton;
        "cc-headline": CcHeadline;
        "cc-icon": CcIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cc-button": LocalJSX.CcButton & JSXBase.HTMLAttributes<HTMLCcButtonElement>;
            "cc-headline": LocalJSX.CcHeadline & JSXBase.HTMLAttributes<HTMLCcHeadlineElement>;
            "cc-icon": LocalJSX.CcIcon & JSXBase.HTMLAttributes<HTMLCcIconElement>;
        }
    }
}
