name: Build and Deploy
on: 
  push:
    paths: ["stories/**", "src/components/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil Components
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Build artifact
        run: tar -czf ${{ runner.temp }}/artifact.tar.gz --exclude ".github" .

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ runner.temp }}/artifact.tar.gz
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull archived artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: 'Extract artifact'
        run: tar -xzf artifact.tar.gz
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Run unit tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Pull archived artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: 'Extract artifact'
        run: tar -xzf artifact.tar.gz
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: ${{ github.workspace }}/docs
          target-folder: docs